heat_template_version: 2017-09-01  

# INSTANCES
description: Web Server Instances
resources:  
  server: 
    type: OS::Nova::Server
    properties:
      name: openstack-nginx-node1
      image: 'CentOS-7-x86_64'
      flavor: m1.medium.cpu-shared
      key_name: cloud3
      security_groups: [default, global_ssh, global_http] 
      networks:
        - network: private
      user_data:
        str_replace:
          template: |
            #!/bin/bash
            #rpm -ivh http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm
            yum -y update
            yum install -y httpd
            systemctl enable httpd
            systemctl start httpd
            #sed '$ a Welcome to nginx1!' /usr/share/nginx/html/index.html
            #sudo mv /usr/share/nginx/html/index.html /usr/share/nginx/html/index.html.bkp
            #sudo touch /usr/share/nginx/html/index.html
            echo 'OpenStack-Apache-1' > /var/www/html/index.html
          params:
           $shared_ip: flavor
           
      name: openstack-nginx-node2
      image: 'CentOS-7-x86_64'
      flavor: m1.medium.cpu-shared
      key_name: cloud3
      security_groups: [default, global_ssh, global_http] 
      networks:
        - network: private
      user_data:
        str_replace:
          template: |
            #!/bin/bash
            rpm -ivh http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm
            yum -y update
            yum install -y nginx
            systemctl enable nginx
            systemctl start nginx
            sed '$ a Welcome to nginx2!' /usr/share/nginx/html/index.html
          params:
           $shared_ip: flavor

   
   
   
